# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1.3

      - run: npm ci --ignore-scripts
      - run: npm run prebuild
      - run: del /s /q src
      - run: del /s /q .github
      - run: del /q .prettierrc.json
      - run: del /q CHANGELOG.md
      - run: del /q README.md
      - run: del /q tsconfig.json
      - run: del /q .eslintrc.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
