# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1.3

      - run: npm ci --ignore-scripts
      - run: npm config set msvs_version 2019
      - run: npm run prebuild -- --upload ${{secrets.PREBUILD_TOKEN}}
      - run: npm run build:ts
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_PACKAGE_TOKEN}}
